services:
  server: 
    build: ./server
    restart: always
    depends_on:
      - postgresql
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: postgresql
      DB_USERNAME: postgres
      DB_DATABASE: postgres
    networks:
      - public
      - database
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.services.timeless-server.loadbalancer.server.port=3000
      - traefik.http.routers.timeless-server.rule=Host(`timeless.ariolandi.com`)&&PathPrefix(`/api`)
      - traefik.http.middlewares.timeless-server-prefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.timeless-server-scheme.redirectscheme.scheme=https
      - traefik.http.routers.timeless-server.middlewares=timeless-server-scheme,timeless-server-prefix
      - traefik.http.routers.timeless-server.tls=true
      - traefik.http.routers.timeless-server.tls.certresolver=ariolandi-com
      - traefik.http.routers.timeless-server.tls.domains[0].main=timeless.ariolandi.com
    
  postgresql:
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - /home/stella/data/timeless:/var/lib/postgresql/data
    networks:
      - database

  client:
    build:
      context: ./client
      args:
        VITE_SERVER_HOST: $VITE_SERVER_HOST
    restart: always
    depends_on:
      - server
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.services.timeless-client.loadbalancer.server.port=8080
      - traefik.http.routers.timeless-client.rule=Host(`timeless.ariolandi.com`)
      - traefik.http.middlewares.timeless-client.redirectscheme.scheme=https
      - traefik.http.routers.timeless-client.middlewares=timeless-client
      - traefik.http.routers.timeless-client.tls=true
      - traefik.http.routers.timeless-client.tls.certresolver=ariolandi-com
      - traefik.http.routers.timeless-client.tls.domains[0].main=timeless.ariolandi.com

networks:
  public:
    external: true
  database:

